import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function Privacy() {
    return (
        <>
            <Navbar />
            <main className="min-h-screen pt-32 pb-24 bg-paper font-inter text-ink">
                <div className="max-w-3xl mx-auto px-6">

                    <header className="mb-12">
                        <Link href="/" className="inline-flex items-center text-sm font-bold text-ink/60 hover:text-ink mb-8 transition-colors">
                            ← Back to Home
                        </Link>
                        <h1 className="text-4xl md:text-5xl font-playfair font-bold mb-4">Privacy Policy</h1>
                        <p className="text-ink/60">Last Updated: December 22, 2025</p>
                    </header>

                    <div className="p-6 bg-gold/10 border border-gold/20 rounded-xl mb-12">
                        <strong className="block font-bold text-lg mb-1">The Short Version</strong>
                        <p className="text-ink/80">Liberry does not collect, store, share, or sell your personal data. You are not the product.</p>
                    </div>

                    <div className="space-y-12 leading-relaxed text-lg text-ink/90">

                        <section>
                            <h2 className="text-2xl font-playfair font-bold mb-4">1. Introduction</h2>
                            <p>Thank you for using <span className="font-semibold">Liberry</span>. We believe that your privacy is paramount. This Privacy Policy describes how we handle your information.</p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-playfair font-bold mb-4">2. Information Collection and Use</h2>
                            <p className="mb-4 font-bold">We do not collect any personal information.</p>
                            <p className="mb-4">When you download and use Liberry, we do not require you to provide any information and we do not collect any information about you or your device.</p>
                            <ul className="list-disc pl-6 space-y-2 marker:text-gold">
                                <li><strong>No User Accounts:</strong> We do not require you to create an account.</li>
                                <li><strong>No Analytics:</strong> We do not use third-party analytics services to track your usage.</li>
                                <li><strong>No Advertising:</strong> We do not display ads and do not collect data for advertising purposes.</li>
                                <li><strong>No Location Tracking:</strong> We do not request or access your location data.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-playfair font-bold mb-4">3. Data Storage</h2>
                            <p className="mb-4">All data generated by the app (such as bookmarks, reading progress, highlights, or settings) is stored strictly <strong>locally on your device</strong>.</p>
                            <p>This data is never transmitted to our servers (because we do not have servers) or any third party. If you delete the app, this local data will be deleted from your device (unless you have backed it up manually with a sync file creation).</p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-playfair font-bold mb-4">4. Device Permissions</h2>
                            <p className="mb-4">To function as an eBook reader, Liberry requests access to specific permissions on your device. These are used solely for functionality:</p>
                            <ul className="list-disc pl-6 space-y-2 marker:text-gold">
                                <li><strong>Storage / Files Access:</strong> We request access to your device's storage to allow you to create and link a sync file. We do not access any files than those which you explicitly select.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-playfair font-bold mb-4">5. Children’s Privacy</h2>
                            <p>Since we do not collect any data from any user, we strictly do not knowingly collect personal information from children under the age of 13.</p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-playfair font-bold mb-4">6. Changes to This Privacy Policy</h2>
                            <p>We may update our Privacy Policy from time to time. We advise you to review this page periodically for any changes. Changes are effective immediately after they are posted on this page.</p>
                        </section>

                        <section className="pt-12 border-t border-gray-200">
                            <h2 className="text-2xl font-playfair font-bold mb-4">Contact Us</h2>
                            <p className="mb-2">If you have any questions or suggestions about this Privacy Policy, do not hesitate to contact us at:</p>
                            <a href="mailto:ceramic_mug@outlook.com" className="text-gold hover:underline font-medium">ceramic_mug@outlook.com</a>
                        </section>

                    </div>
                </div>
            </main>
            <Footer />
        </>
    );
}
